### ISSUE TITLE
about ctr prediction metric

### ISSUE THREAD

**Issue by weberrr** [AmazingDD/daisyRec#1]
This is a good project!
But can u add some ctr prediction metrics such as 'AUC' or 'F1'？
I think add it is easy, and it will be more helpful.

**Comment by yudi-mars** [comment]
Thx,  this code now only consider the most popular metric in rank issue and all metrics are in `daisy.utils.metrics`. For your issue, I think F1-score could be calculated by precision and recall, and AUC is also available in other way.
This version of daisy is still an experimental code, not a package. Therefore, I will update and release it to a more complete version after our paper got published.
I will update these metrics after Feb. 2020，and you can also fork this repo and add these metrics. I'd like merge your request.

**Comment by yudi-mars** [comment]
> This is a good project!
> But can u add some ctr prediction metrics such as 'AUC' or 'F1'？
> I think add it is easy, and it will be more helpful.

I've already update `metrics.py`, add new metrics like AUC, F1-score. Enjoy it!

https://github.com/AmazingDD/daisyRec/blob/f8b76cad2339fb3d9709ca6a4f3080e949b0daab/daisy/utils/metrics.py#L121

https://github.com/AmazingDD/daisyRec/blob/f8b76cad2339fb3d9709ca6a4f3080e949b0daab/daisy/utils/metrics.py#L140
