### ISSUE TITLE
ModuleNotFoundError: No module named '...'

### ISSUE THREAD

**Issue by Jadiker** [AmazingDD/daisyRec#16]
I followed the instructions to run the project, but immediately ran into `ModuleNotFoundError: No module named 'optuna'`. Did I miss an install somewhere?

If I didn't miss anything, which version of `optuna` should I use, and can this be included in the `requirements.txt`?

**Comment by Jadiker** [comment]
Same issue but with `requests`:
```
Traceback (most recent call last):
  File "daisyRec\tune.py", line 20, in <module>
    from daisy.utils.loader import RawDataReader, Preprocessor
  File "daisyRec\daisy\utils\loader.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by yudi-mars** [comment]
I think both 'requests' and `optuna` modules could be installed via pip or conda, it's an environment problem.
