### ISSUE TITLE
Bug in CDAE model about out_activation

### ISSUE THREAD

**Issue by 2017pxy** [AmazingDD/daisyRec#4]
I notice that in your CDAERecommender.py (line 69-70), no matter the `out_activation` is `sigmoid` or `relu`, it is always set as `nn.Sigmoid()`. I am not sure if this is a type error?

https://github.com/AmazingDD/daisyRec/blob/dev/daisy/model/CDAERecommender.py

**Comment by yudi-mars** [comment]
Yes, and I just fix this bug. Thx for your scrutiny!
