### ISSUE TITLE
Paper availability?

### ISSUE THREAD

**Issue by deklanw** [AmazingDD/daisyRec#5]
Hi,

I'm interested in reading the associated paper "Are We Evaluating Rigorously?" but I can't seem to find it anywhere. Is it available openly?

Thanks

**Comment by xinghua-qu** [comment]
Hi,

Thanks for your interest in our paper.
The link for your access to our paper could be https://dl.acm.org/doi/pdf/10.1145/3383313.3412489?casa_token=B9qEYqCm_GEAAAAA:29dp2HP8EYG6dbUOCOZwmw4q2vd8T6Fe374uaWxx76iBtljE-9uFPTjjC-T8YFiYPQlKJQZUTTxEyQ
You may also refer to the PDF attached for reading.
[Are We Evaluating Regorously.pdf](https://github.com/AmazingDD/daisyRec/files/5790770/Are.We.Evaluating.Regorously.pdf)

**Comment by deklanw** [comment]
Thank you!
