### ISSUE TITLE
the parameter test_method='ufo' in daisy.utils.splitter.split_test()

### ISSUE THREAD

**Issue by DiveGu** [AmazingDD/daisyRec#6]
In your fuction split_test(), parameter test_method='ufo' means : split by ratio in user level.
I think the 'ufo' should let 20% of each user's interaction records be the test set. In your fuction, let 20% of users' interactions as test set, so that user' embedding in the test set are not trained...

**Comment by yudi-mars** [comment]
Yes, and I just update this split method. But I'm not sure whether this code will perform well in big dataset.
If you have any better thought or solution, please help me and I'll merge your code
