### ISSUE TITLE
Why can MRR be bigger than 1?

### ISSUE THREAD

**Issue by liuqidong07** [AmazingDD/daisyRec#9]
Hello, I have read your paper and find it is a fantastic work. However, I find mrr metric is bigger than 1 in your result such as ML1M. But in my view, it can not be greater than 1. Can you clear up my confusion, thanks!

Qidong Liu
Best wishes!

**Comment by yudi-mars** [comment]
it depends on the method to calculate this metric. In my view, there are 2 ways to calculate MRR but we just choose one. You can see the metrics.py to get further discussion.

**Comment by yudi-mars** [comment]
https://github.com/AmazingDD/daisyRec/blob/1b7d693f07b892f26eb026d416d86a59a6c3e3a0/daisy/utils/metrics.py#L53
